name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *' # twice a day 
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: fm-sys:master
          head: RobinLinus:master
          pr_title: "Update Snapdrop Fork" 
